package dev.blokz.arxiver.core.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Fts4
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * SPEC-DATA §4 / SPEC-SEARCH §8 — per-paper text chunk + its L2-normalized
 * float32 embedding (RAG retrieval, P2.1). Mirrors [PaperEmbeddingEntity]'s BLOB
 * layout and per-row model guard, but is chunk-grained: a paper's abstract and
 * each note split into bounded chunks, one row per chunk.
 *
 * The autogenerated [id] is the rowid the external-content [ChunkFtsEntity] maps
 * to. `(paper_id, source_kind, ordinal)` is unique so re-indexing a paper is a
 * delete-then-insert rather than relying on the synthetic key.
 */
@Entity(
    tableName = "chunk_embeddings",
    foreignKeys = [
        ForeignKey(
            entity = PaperEntity::class,
            parentColumns = ["id"],
            childColumns = ["paper_id"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [
        Index("paper_id"),
        Index(value = ["paper_id", "source_kind", "ordinal"], unique = true),
    ],
)
data class ChunkEmbeddingEntity(
    @PrimaryKey(autoGenerate = true) @ColumnInfo(name = "id") val id: Long = 0,
    @ColumnInfo(name = "paper_id") val paperId: String,
    @ColumnInfo(name = "chunk_text") val chunkText: String,
    @ColumnInfo(name = "vector", typeAffinity = ColumnInfo.BLOB) val vector: ByteArray,
    @ColumnInfo(name = "model") val model: String,
    @ColumnInfo(name = "dim") val dim: Int,
    @ColumnInfo(name = "source_kind") val sourceKind: String,
    @ColumnInfo(name = "ordinal") val ordinal: Int,
    @ColumnInfo(name = "embedded_at") val embeddedAt: Long,
) {
    override fun equals(other: Any?): Boolean =
        other is ChunkEmbeddingEntity &&
            other.paperId == paperId &&
            other.sourceKind == sourceKind &&
            other.ordinal == ordinal &&
            other.vector.contentEquals(vector)

    override fun hashCode(): Int = (paperId.hashCode() * 31 + sourceKind.hashCode()) * 31 + ordinal

    companion object {
        /** `abstract` (title+abstract) and `note` (note body) chunk provenance. */
        const val SOURCE_ABSTRACT = "abstract"
        const val SOURCE_NOTE = "note"

        /** Full paper-body text extracted from the reader HTML (P-FullText PFT.2) — the third indexed source. */
        const val SOURCE_BODY = "body"
    }
}

/**
 * External-content FTS4 index over chunk text (SPEC-SEARCH §8 keyword leg). Room
 * generates and maintains the sync triggers against [ChunkEmbeddingEntity]; the
 * FTS rowid mirrors `chunk_embeddings.id`.
 */
@Fts4(contentEntity = ChunkEmbeddingEntity::class)
@Entity(tableName = "chunk_fts")
data class ChunkFtsEntity(
    @ColumnInfo(name = "chunk_text") val chunkText: String,
)
